// Generated by https://quicktype.io

using System;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace CRM.DAL.Models.ResponseModels.Sia
{
  public partial class WalletResponse
  {
    [JsonProperty("encrypted")]
    public bool Encrypted { get; set; }

    [JsonProperty("unlocked")]
    public bool Unlocked { get; set; }

    [JsonProperty("rescanning")]
    public bool Rescanning { get; set; }

    [JsonProperty("confirmedsiacoinbalance")]
    public long Confirmedsiacoinbalance { get; set; }

    [JsonProperty("unconfirmedoutgoingsiacoins")]
    public long Unconfirmedoutgoingsiacoins { get; set; }

    [JsonProperty("unconfirmedincomingsiacoins")]
    public long Unconfirmedincomingsiacoins { get; set; }

    [JsonProperty("siafundbalance")]
    public long Siafundbalance { get; set; }

    [JsonProperty("siacoinclaimbalance")]
    public long Siacoinclaimbalance { get; set; }

    //@TODO: convert to numeric type 
    [JsonProperty("dustthreshold")]
    public string Dustthreshold { get; set; }
  }
}
